CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    classe VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    account_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    grade INT NOT NULL
);
